module.exports = {
	extends: ["stylelint-prettier"],
	rules: {
		"at-rule-no-unknown": true,
		"at-rule-semicolon-space-before": "never",
		"block-closing-brace-newline-before": "always",
		// "block-closing-brace-space-before": "never",
		"block-no-empty": true,
		"block-opening-brace-newline-after": "always",
		// The following lines conflict with other, more pertinent rules
		// "block-opening-brace-newline-before": "never-multi-line",
		// "block-opening-brace-space-after": "never",
		"color-hex-length": "long",
		"color-named": "never",
		"color-no-invalid-hex": true,
		"comment-no-empty": true,
		"declaration-block-no-duplicate-properties": true,
		"declaration-block-no-redundant-longhand-properties": true,
		"declaration-block-no-shorthand-property-overrides": true,
		"declaration-block-semicolon-newline-after": "always",
		"declaration-block-semicolon-newline-before": "never-multi-line",
		// "declaration-block-semicolon-space-after": "never",
		"declaration-colon-space-after": "always",
		"declaration-no-important": true,
		"font-family-name-quotes": "always-where-required",
		"font-family-no-duplicate-names": true,
		"font-weight-notation": "numeric",
		"function-calc-no-invalid": true,
		"function-calc-no-unspaced-operator": true,
		"function-comma-newline-after": "never-multi-line",
		"function-comma-space-after": "always",
		"function-linear-gradient-no-nonstandard-direction": true,
		"function-parentheses-newline-inside": "never-multi-line",
		"function-parentheses-space-inside": "never",
		"function-url-quotes": "always",
		// indentation: "tab",
		"keyframe-declaration-no-important": true,
		"media-feature-name-no-unknown": true,
		"no-descending-specificity": true,
		"no-duplicate-at-import-rules": true,
		"no-duplicate-selectors": true,
		"no-empty-first-line": true,
		"no-extra-semicolons": true,
		"no-empty-source": true,
		"no-invalid-double-slash-comments": true,
		"property-no-unknown": true,
		"selector-attribute-operator-space-after": "always",
		"selector-attribute-operator-space-before": "always",
		"selector-attribute-quotes": "always",
		"selector-pseudo-class-no-unknown": true,
		"selector-pseudo-element-no-unknown": true,
		"selector-type-no-unknown": true,
		"shorthand-property-no-redundant-values": true,
		"string-quotes": "double",
		"unit-no-unknown": true,
		"value-list-comma-newline-after": "never-multi-line",
		"value-list-comma-newline-before": "never-multi-line",
		"value-keyword-case": "lower"
	}
}
